theme: jekyll-theme-cayman
title: Multi-threaded pipelined Chia k32 plotter build for Windows
description: This is a new implementation of a chia plotter which is designed as a processing pipeline, similar to how GPUs work, only the “cores” are normal software CPU threads. As a result this plotter is able to fully max out any storage device’s bandwidth, simply by increasing the number of “cores”, ie. threads
show_downloads: true
